name: go test

on: [push]

jobs:
  go-test:
    name: go-test
    runs-on: ubuntu-latest
    steps:
      - name: set up go 1.14
        uses: actions/setup-go@v1
        with:
          go-version: 1.14

      - name: checkout
        uses: actions/checkout@v1

      - name: go test
        run: make test
